# Generated by Django 4.0.1 on 2022-01-27 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_remove_room_reserved_by_reserve'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserve',
            options={'ordering': ['-reserve_from']},
        ),
    ]
